import Head from "next/head";
import { listByCoach } from "../../mongo";
import styles from "../../styles/Home.module.css";

export const getServerSideProps = async ({ params }) => {
  const { name } = params;
  const data = JSON.parse(JSON.stringify(await listByCoach(name)));
  console.log(data);
  return {
    props: {
      name,
      data,
    },
  };
};

export default function Uni({ name, data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{name} - KCSoc Retreats</title>
        <meta name="description" content="Generated by kcsoc" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          onClick={() => {
            window.location.href = "/coaches";
          }}
        >
          Back
        </button>
        <h2 className={styles.title}>{`${name} (${data.length})`}</h2>
        <br></br>
        <table border={1} cellPadding={10}>
          <tbody>
            <tr>
              <th>Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>University</th>
            </tr>
            {data.map((item) => (
              <tr
                key={
                  item["Product Form: Name"] +
                  item["Product Form: Last Name"]
                }
              >
                <td>{item["Product Form: Name"]}</td>
                <td>{item["Product Form: Last Name"]}</td>
                <td>{item["Email"]}</td>
                <td>{item["Product Form: Mobile Number"]}</td>
                <td>{item["Product Form: University"]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}
