import Head from "next/head";
import Image from "next/image";
import FileUpload from "../Upload";
import styles from "../../styles/Home.module.css";
import { countCoaches, distinct } from "../../mongo";

export async function getServerSideProps() {
  let data;
  data = await distinct("Product Form: Are you interested in a coach service from any of the following locations?");
  data = await countCoaches(data);
  data = data.sort((a, b) => b.count - a.count);
  const otherObj = data.find((element) => element.uni === "Other");
  console.log(otherObj);
  data.push(data.splice(data.indexOf(otherObj), 1)[0]);
  console.log(data);

  if (data.length === 1 && data[0] === undefined) {
    console.log("no data");
    return { props: { data: [] } };
  }

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>KCSoc Retreats</title>
        <meta name="description" content="Generated by kcsoc" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          onClick={() => {
            window.location.href = "/";
          }}
        >
          Back
        </button>

        <h2 className={styles.title}>Coach Options</h2>
        <table border={1} cellPadding={10}>
          <tbody>
            <tr>
              <th>Coach Option</th>
              <th>Sign Ups</th>
              <th>More Info</th>
            </tr>
            {data.map((uni, index) => (
              <tr key={uni.coach}>
                <td>{uni.coach}</td>
                <td>{uni.count}</td>
                <td>
                  <button
                    style={{
                      backgroundColor: "#d0cfcf !important",
                    }}
                    onClick={() => {
                      window.location.href = `/coaches/${uni.coach}`;
                    }}
                  >
                    View Info
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}
