import Head from "next/head";
import { list } from "../../mongo";
import styles from "../../styles/Home.module.css";

export const getServerSideProps = async ({ params }) => {
  const { name } = params;
  const data = JSON.parse(JSON.stringify(await list(name)));
  console.log(data);
  return {
    props: {
      name,
      data,
    },
  };
};

export default function Uni({ name, data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{name} - KCSoc Flagships</title>
        <meta name="description" content="Generated by kcsoc" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          onClick={() => {
            window.location.href = "/";
          }}
        >
          Back
        </button>
        <h2 className={styles.title}>{name}</h2>
        <br></br>
        <table border={1} cellPadding={10}>
          <tbody>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
            </tr>
            {data.map((item) => (
              <tr key={item["First Name"] + item["Lastname"]}>
                <td>{item["First Name"]}</td>

                <td>{item["Surname"]}</td>
                <td>{item["Email"]}</td>
                <td>{item["Mobile Phone"]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}
