import Head from "next/head";
import Image from "next/image";
import FileUpload from "./Upload";
import { countUnis, distinct } from "../mongo";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  let data;
  data = await distinct();
  data = await countUnis(data);
  data = data.sort((a, b) => b.count - a.count);
  const otherObj = data.find((element) => element.uni === "Other");
  console.log(otherObj);
  data.push(data.splice(data.indexOf(otherObj), 1)[0]);
  console.log(data);

  if (data.length === 1 && data[0] === undefined) {
    console.log("no data");
    return { props: { data: [] } };
  }

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>KCSoc Retreats</title>
        <meta name="description" content="Generated by kcsoc" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img
          className={styles.logo}
          src="/logo.png"
          alt="KCSoc Logo"
          width="200"
        />

        <h2 className={styles.title}>Welcome to KCSoc Retreats!</h2>
        <table border={1} cellPadding={10}>
          <tbody>
            <tr>
              <th>Position</th>
              <th>University</th>
              <th>Sign Ups</th>
              <th>More Info</th>
            </tr>
            {data.map((uni, index) => (
              <tr key={uni.uni}>
                <td>{index + 1}</td>
                <td>{uni.uni}</td>
                <td>{uni.count}</td>
                <td>
                  <button
                    style={{
                      backgroundColor: "#d0cfcf !important",
                    }}
                    onClick={() => {
                      window.location.href = `/uni/${uni.uni}`;
                    }}
                  >
                    View Info
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <FileUpload />
        <br/>
        <br/>
        <button onClick={()=>{
          window.location.href="/all";
        }}
        >
          View All Data
        </button>
      </main>
    </div>
  );
}
